name: Build Custom Textbee Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2 # SHA pinned version
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0 # SHA pinned version
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Update API Base URL
        run: |
          FILE_PATH="android/app/src/main/java/com/vernu/sms/AppConstants.java"
          NEW_URL="http://144.172.92.232:3001/api/v1/"
          ESCAPED_NEW_URL=$(printf '%s\n' "$NEW_URL" | sed -e 's/[\/&]/\\&/g')
          sed -i "s|public static final String API_BASE_URL = \".*\";|public static final String API_BASE_URL = \"$ESCAPED_NEW_URL\";|" "$FILE_PATH"
          echo "✅ Updated API_BASE_URL:"
          grep 'API_BASE_URL' "$FILE_PATH"

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug --stacktrace --info

      - name: List APKs
        run: ls -alh android/app/build/outputs/apk/debug || echo "APK folder not found"

      - name: Upload Debug APK
        if: success()
        uses: actions/upload-artifact@v3.1.3 # SHA pinned version
        with:
          name: textbee-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Print Gradle logs
        run: cat android/app/build/reports/build.log || echo "No build log found"
